# Site settings
title: idioteque
description: >
  a minimal theme for Jekyll static site generator

# Baseurl: "/" # the subpath of your site, e.g. /blog/
url: "/" # the base hostname & protocol for your site
permalink: "/blog/:title/"
author:
  fullname: Tony R
  #googleplus:
  github: tonyynot
  twitter: tonecodes
  disqus:
  instagram:
  linkedin:

google_analytics: 'UA-________' #Your Google Analytics tracking ID goes here

# Comments settings - see staticman.yml for configurations
github_repo:
github_branch:
comments_redirect:

# Build settings
# Do not change or stuff will break
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]
