# Site settings
title: idioteque
description: >
  a curated web developer blog with resources, articles and opinions by Anthony Ramella

# Baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://anthonyramella.com" # the base hostname & protocol for your site
permalink: "/blog/:title/"
author:
  fullname: Anthony Ramella
  #googleplus:
  github: tonyynot
  twitter: tonecodes
  disqus: aramella
  instagram: blankwaves
  linkedin: alramella

google_analytics: 'UA-________' #Your Google Analytics tracking ID goes here

# Staticman (static comments)
allowedFields: ['name', 'email', 'comment']
branch: 'gh-pages'
filename: entry{@timestamp}
format: 'json'
path: "_data/comments"
moderation: true
requiredFields: ['name', 'comment']
transforms:
  email: 'md5'

# Build settings
# Do not change or stuff will break
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]

gems:
  - jekyll-gist
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - font-awesome-sass
